reporter: "xcode"

excluded:
  - DerivedData
  - Pods
  - Screenshots/SnapshotHelper.swift

disabled_rules:
  - identifier_name
  - type_name
  - weak_delegate
  - trailing_whitespace
  - class_delegate_protocol
  - todo
  - nesting

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - last_where
  - legacy_multiple
  - mark
  - modifier_order
  - nslocalizedstring_key
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - unowned_variable_capture
  - unused_import
  - vertical_whitespace_between_cases

force_try:
  severity: error

force_unwrapping:
  severity: error

line_length:
  warning: 120
  ignores_comments: true

type_body_length:
  warning: 400

