lane :pull_request do
    run_tests(
        workspace: "Eurofurence.xcworkspace",
        scheme: "Eurofurence",
        device: "iPhone 8 Plus",
        derived_data_path: "./DerivedData"
    )
    
    danger(
        danger_id: "eurofurence-mobileapps-ci",
        dangerfile: "Dangerfile",
        github_api_token: ENV['DANGER_PERSONAL_ACCESS_TOKEN']
    )
end

lane :screenshots do
    capture_screenshots(stop_after_first_error: true)
end
