devices([
   "iPhone SE (3rd generation)",
   "iPhone 8",
   "iPhone 8 Plus",
   "iPhone 13",
   "iPhone 13 Pro Max",

   "iPad Pro (9.7-inch)",
   "iPad Pro (11-inch) (3rd generation)",
   "iPad Pro (12.9-inch) (2nd generation)",
   "iPad Pro (12.9-inch) (5th generation)"
])

languages([
  "en-US"
])

workspace("Eurofurence.xcworkspace")
scheme("Eurofurence")
testplan("Screenshots")
output_directory("./screenshots")
clear_previous_screenshots(true) 
override_status_bar(true)


