devices([
   "iPhone SE (3rd generation)",
   "iPhone 14",
   "iPhone 14 Pro Max",

   "iPad Pro (11-inch) (4th generation)",
   "iPad Pro (12.9-inch) (6th generation)"
])

languages([
  "en-US"
])

project("Eurofurence.xcodeproj")
scheme("Eurofurence")
testplan("Screenshots")
output_directory("./screenshots")
clear_previous_screenshots(true) 
override_status_bar(true)


