devices([
   "iPhone 8 Plus",
   "iPhone 14",
   "iPhone 14 Pro Max",

   "iPad Pro (11-inch) (4th generation)",
   "iPad Pro (12.9-inch) (4th generation)",
   "iPad Pro (12.9-inch) (6th generation)"
])

languages([
  "en-US"
])

project("Eurofurence.xcodeproj")
scheme("Eurofurence")
testplan("Screenshots")
output_directory("./screenshots")
clear_previous_screenshots(true) 
reinstall_app(true)
erase_simulator(true)
app_identifier("org.eurofurence")
override_status_bar(true)
concurrent_simulators(3)

